name: C/C++ Premake Saturn Compilation
run-name: ${{ github.actor }}
on: [push]
jobs:
  COMPILE-WINDOWS:
    runs-on: [Windows, X64]
    steps: 
      - uses: actions/checkout@v2
      - name: Build binaries.
        run: call ${{ github.workspace }}/generate_projects.bat
        shell: cmd
